version: '3'
services:
  web:
    build: .
    ports:
      - "8080:80"

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://host.docker.internal:27017
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: user_todos
#      MONGO_INITDB_ROOT_PASSWORD: pAsw0Rd
    ports:
      - 27017:27017
#    networks:
#      - dropw-mongodb-ntw

#  nginx:
#    image: nginx
#    container_name: nginx
#    volumes:
#    - ./nginx.conf:/etc/nginx/nginx.conf
#    ports:
#    - "8080:80"
#    - "443:443"
#    networks:
#    - dropw-mongodb-ntw

#  dropw-ms:
#    image: openjdk:8-jre
#    container_name: dropw-ms
#    volumes:
#    - ./target/dropwizardArtifactId-1.0-SNAPSHOT.jar
#    - ./todo-list.yml
#    working_dir: /dropwizardArtifactId
#    command: ["java", "-jar", "dropwizardArtifactId-1.0-SNAPSHOT.jar", "server", "todo-list.yml"]
#    ports:
#    - "8090:8080"
#    - "8091:8081"
#    networks:
#    - dropw-mongodb-ntw

#networks:
#  dropw-mongodb-ntw:
#    external:
#      name: dropw-mongodb-ntw